### PR TITLE
Cucumber 7

### PR DESCRIPTION
**Pull request by jbpros**
As announced, this PR is based off #15. All the existing tests are passing. The codebase has been mostly rewritten (and is in TypeScript), and the tests have undergone some refactoring.

This is currently a draft as I still need to implement support for the [`Rule` keyword](https://cucumber.io/docs/gherkin/reference/#Rule).

Feedback welcome!

/cc @aslakhellesoy @mattwynne @davidjgoss @charlierudolph @sebrose @tooky

### CODE REVIEW

**Comment by jbpros** [comment]
And as noted on #15, this is now building on [GitHub actions](https://github.com/jbpros/cucumber-pretty/actions?query=workflow%3Abuild).

**Comment by jbpros** [comment]
I'd like to thank you @sebrose for the [investigative work](https://github.com/cucumber-ltd/shouty.js/blob/cucumber-pretty/simple_formatter.js) you did on this, it has been useful to find my ways in the message protocol and the existing helpers.

**Comment by jbpros** [comment]
`Rule` keyword added. I think this is good to go!

Supersedes #15.

**Comment by mattwynne** [comment]
👏 thanks @jbpros

**Comment by aslakhellesoy** [comment]
Brilliant @jbpros!

This could also be a good basis for a cross-platform implementation later.

**Comment by jbpros** [comment]
@aslakhellesoy thanks — that was my secret wish! I’d love to go through the code with you and see if I did something weird. I’m still new to all this cucumber message business and there might be better approaches to getting the data we need.

**Comment by mattwynne** [comment]
> I’d love to go through the code with you and see if I did something weird. I’m still new to all this cucumber message business and there might be better approaches to getting the data we need.

It would also be useful to see if there's any abstractions we should push upstream into the Gherkin library to make this kind of thing easier for other use-cases.

**Comment by jbpros** [comment]
See https://github.com/kozhevnikov/cucumber-pretty/pull/17#issuecomment-756430339

**Pull request closed without merging**
